[package]
name = "iotkit-output-adapter-pinikiet-mqtt-v1"
version.workspace = true
edition = "2024"
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
iotkit-output-adapter-api = { path = "../api" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }

[dev-dependencies]
iotkit-output-adapter-testkit = { path = "../testkit" }
