[package]
name = "iotkit-gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
iotkit-core-types = { path = "../core/types" }
iotkit-core-engine = { path = "../core/engine" }
bravepi-adapter = { path = "../bravepi-adapter" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
