package store

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
)

func openPostgres(dsn string, configuredEdgeID string) (*Store, error) {
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		return nil, errors.New("open PostgreSQL storage")
	}
	db.SetMaxOpenConns(20)
	ctx := context.Background()
	if err := db.PingContext(ctx); err != nil {
		_ = db.Close()
		return nil, errors.New("connect PostgreSQL storage")
	}
	if err := applyPostgresMigrations(ctx, db, configuredEdgeID); err != nil {
		_ = db.Close()
		return nil, err
	}
	store := &Store{
		db:          &sqlDatabase{raw: db, dialect: dialectPostgres},
		profile:     ProfilePostgres,
		postgresDSN: dsn,
	}
	if err := store.validateConfiguredEdgeIdentity(ctx, configuredEdgeID); err != nil {
		_ = db.Close()
		return nil, err
	}
	if err := store.validateEdgeIdentity(ctx); err != nil {
		_ = db.Close()
		return nil, err
	}
	return store, nil
}

func (store *Store) validateConfiguredEdgeIdentity(ctx context.Context, configuredEdgeID string) error {
	if configuredEdgeID == "" {
		return nil
	}
	var storedEdgeID string
	if err := store.db.QueryRowContext(ctx,
		"SELECT edge_id FROM edge_meta WHERE singleton = 1",
	).Scan(&storedEdgeID); err != nil {
		return err
	}
	if storedEdgeID != configuredEdgeID {
		return errors.New("configured IoTKit Edge ID does not match the existing database")
	}
	return nil
}

func applyPostgresMigrations(ctx context.Context, db *sql.DB, configuredEdgeID string) error {
	if _, err := db.ExecContext(ctx, postgresCompatibilitySQL); err != nil {
		return fmt.Errorf("initialize PostgreSQL compatibility functions: %w", err)
	}
	if _, err := db.ExecContext(ctx, `
		CREATE TABLE IF NOT EXISTS edge_schema_meta (
			singleton INTEGER PRIMARY KEY CHECK(singleton = 1),
			version INTEGER NOT NULL
		);
		INSERT INTO edge_schema_meta(singleton, version) VALUES(1, 0)
		ON CONFLICT(singleton) DO NOTHING;
	`); err != nil {
		return fmt.Errorf("initialize PostgreSQL schema metadata: %w", err)
	}
	var current int
	if err := db.QueryRowContext(ctx,
		"SELECT version FROM edge_schema_meta WHERE singleton = 1",
	).Scan(&current); err != nil {
		return fmt.Errorf("read PostgreSQL Edge schema version: %w", err)
	}
	latest := schemaMigrations[len(schemaMigrations)-1].version
	if current > latest {
		return fmt.Errorf("Edge schema version %d is newer than supported version %d", current, latest)
	}
	for _, migration := range schemaMigrations {
		if migration.version <= current {
			continue
		}
		tx, err := db.BeginTx(ctx, nil)
		if err != nil {
			return fmt.Errorf("begin PostgreSQL Edge schema migration %d: %w", migration.version, err)
		}
		migrationSQL := postgresMigrationSQL(migration.sql)
		if migrationSQL != "" {
			if _, err := tx.ExecContext(ctx, migrationSQL); err != nil {
				_ = tx.Rollback()
				return fmt.Errorf("apply PostgreSQL Edge schema migration %d: %w", migration.version, err)
			}
		}
		if migration.version == 11 && configuredEdgeID != "" {
			if _, err := tx.ExecContext(ctx,
				"UPDATE edge_meta SET edge_id = $1 WHERE singleton = 1",
				configuredEdgeID,
			); err != nil {
				_ = tx.Rollback()
				return fmt.Errorf("assign configured Edge identity in PostgreSQL migration 11: %w", err)
			}
		}
		if _, err := tx.ExecContext(ctx,
			"UPDATE edge_schema_meta SET version = $1 WHERE singleton = 1",
			migration.version,
		); err != nil {
			_ = tx.Rollback()
			return fmt.Errorf("record PostgreSQL Edge schema migration %d: %w", migration.version, err)
		}
		if err := tx.Commit(); err != nil {
			return fmt.Errorf("commit PostgreSQL Edge schema migration %d: %w", migration.version, err)
		}
		current = migration.version
	}
	return nil
}

func postgresMigrationSQL(source string) string {
	statements := strings.Split(source, ";")
	converted := make([]string, 0, len(statements))
	for _, statement := range statements {
		trimmed := strings.TrimSpace(statement)
		upper := strings.ToUpper(trimmed)
		if trimmed == "" || strings.HasPrefix(upper, "INSERT OR IGNORE") {
			continue
		}
		// A PostgreSQL profile is initialized directly at the current schema.
		// Historical data-copy statements operate on empty predecessor tables and
		// are deliberately omitted; edge_meta is the only seed row.
		if strings.Contains(upper, "INSERT INTO") &&
			!strings.HasPrefix(upper, "INSERT INTO EDGE_META") {
			continue
		}
		trimmed = strings.ReplaceAll(trimmed,
			"INTEGER PRIMARY KEY AUTOINCREMENT",
			"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
		)
		trimmed = strings.ReplaceAll(trimmed, "INTEGER", "BIGINT")
		trimmed = strings.ReplaceAll(trimmed, " BLOB", " BYTEA")
		trimmed = strings.ReplaceAll(trimmed, "offset", `"offset"`)
		converted = append(converted, trimmed)
	}
	return strings.Join(converted, ";\n")
}
