[package]
name = "bravepi-poc"
version = "0.1.0"
edition = "2024"
license.workspace = true
repository.workspace = true

[dependencies]
iotkit-core-supervision = { path = "../../core/supervision" }
bravepi-mainboard-adapter = { path = ".." }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
