[package]
name = "rpi-local-adapter"
version = "0.1.0"
edition = "2021"

[dependencies]
iotkit-core-types = { path = "../core/types" }
rpi4b-transport = { path = "../rpi4b-driver/transport" }
bravepi-sensors = { path = "../bravepi-mainboard-adapter/sensors" }
tokio = { version = "1", features = ["sync", "rt", "macros", "time"] }
tracing = "0.1"
